### ISSUE TITLE
JSON export

### ISSUE THREAD

**Issue by jkuchar** [sysnux/btrfs-snapshots-diff#4]
As I wanted to create BTRFS two-way sync tool I also needed to parse there streams.

I have version with outputs JSON data with summary of stram content. If it is useful for someone I can send pull request with this output format.

my version is available here: https://gitlab.grifart.cz/jkuchar1/btrfs-send-parser

**Comment by sysnux** [comment]
Hi Jan,
I'll gladly accept a pull request if json is just an option and old mode is default.

**Comment by darkdragon-001** [comment]
Maybe it makes sense to abstract this away: Make a `commands` interface (base class) which accepts new commands. Then one can inherit from it and save/output in whatever way one wants.

**Comment by sysnux** [comment]
JSON export is available in 6a0209, mostly based on what jkuchar did: thanks!

**Comment by jkuchar** [comment]
Thank you @sysnux ! :-)
