### ISSUE TITLE
CSV output is broken if a filename contains a semicolon

### ISSUE THREAD

**Issue by ceremcem** [sysnux/btrfs-snapshots-diff#7]
### Reproduction 

```
touch "$HOME/hello;there;my;file;is;here"
```

CSV output becomes: 

```
home/ceremcem/hello;renamed from "o7899611-71742-0";owner 1000:1000;mode 644;times a=2021/01/11 12:36:48 m=2021/01/11 12:36:48 c=2021/01/11 12:36:48
o7899612-71742-0;mkfile;rename to "home/ceremcem/hello;there;my;file;is;here"
```

The first column is inaccurate.

**Comment by sysnux** [comment]
Thanks for the report.
Not sure how to resolve the issue, though. Would quoting fields work for you?
For example:
"symlink";"renamed from o260-3437558-0";"xattr security.selinux (117, 110,...

**Comment by ceremcem** [comment]
I think that will not resolve the issue, because a filename may also contain quotation mark. There will always be a magic sequence that breaks the format. 

The separator character (or the quotation mark if you prefer adding it) should be escaped instead. A configurable separator would be nicer. 

If the output can be precisely controlled, then the filename column might be moved to the last column. This would prevent the format to be broken by any magic sequence as well as the need for character escaping.

I think the raw output is great for parsing, I can't see a necessity for a CSV output. I just wanted to report the issue.

**Comment by sysnux** [comment]
Would that be ok?
o261-3441116-0;mkfile;rename to "xxx\;yyy\;zzz"
xxx\;yyy\;zzz;renamed from "o261-3441116-0";xattr security.selinux (117, 110, 99, 111, 110, 102, 105,  ...

**Comment by ceremcem** [comment]
I think CSV output is totally unnecessary. Default output (one at a line, null line terminated) is quite pretty for parsing. Here is a sample parser: 

```sh
#!/bin/bash

event=()  # every single event
while read line; do
    if [[ -n $line ]]; then
        event+=("$line")
        continue
    else
        name=   # file or folder name
        action=   # create, update, delete, rename
        rest= # Currently I don't know all of the fields
        for i in "${event[@]}"; do
            [[ -z $name ]] && { name="$i"; continue; }
            [[ $i =~ ^mkdir ]] && { action="create"; continue; }
            rest="$rest +++ $i"
        done
        event=()
        # ------------------------
        # End of parsing
        # ------------------------
        echo "For: $name action: $action rest is: $rest"
    fi
done <<< $(./btrfs-snapshots-diff.py -p $1 -c $2)
```

**Comment by sysnux** [comment]
CSV output corrected by escaping separator.
